

CREATE TABLE [dbo].[CRUD_OPERATION_TABLE](
	[EMPLOYEE_ID] [int] NOT NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[DESIGNATION] [nvarchar](100) NULL,
	[POST] [nvarchar](100) NULL,
	[PLACE] [nvarchar](100) NULL,
	[PHONE] [nvarchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

